### ISSUE TITLE
"Cannot call hover while not dragging." error on array of files

### ISSUE THREAD

**Issue by davemecha** [Camberi/firecms#156] opened 2021-11-15 16:38 UTC
I created a property for my build schema.

``` ts
    gallery: {
      title: 'Gallery',
      dataType: 'array',
      of: {
        dataType: 'string',
        config: {
          storageMeta: {
            mediaType: 'image',
            storagePath: 'images',
            acceptedFiles: ['image/*'],
            metadata: {
              cacheControl: 'max-age=1000000',
            },
          },
        },
      },
    },
```

When I drag & drop files to the drop zone, I see this error.

![image](https://user-images.githubusercontent.com/137976/141819212-a8fb952b-519f-4e55-8fe6-d86472da4d00.png)
![image](https://user-images.githubusercontent.com/137976/141819292-71d4ebc4-b4a8-48f3-934b-e66292d86601.png)

I use version 1.0.0-beta4

**Comment by fgatti675** [comment] 2021-11-18 21:00
Can't reproduce this one, what version of FireCMS are you on?

**Comment by fgatti675** [comment] 2021-12-13 11:07
Closing this since I can't reproduce it, don't hesitate to reopen if it happens again

**Closed by fgatti675** 2021-12-13 11:07 UTC
