### ISSUE TITLE
Undesired behaviour - Fetching all the documents of a collection

### ISSUE THREAD

**Issue by k00na** [Camberi/firecms#89] opened 2021-06-04 11:07 UTC
Yesterday I played around with FireCMS to test it out and was a bit shocked when I saw this today on Firebase console. 

![Screenshot 2021-06-04 at 13 03 03](https://user-images.githubusercontent.com/13611208/120792013-351d8e00-c535-11eb-9787-cdd9cc8d85ab.png)

Here's the deal:
- I have a collection with 11000 documents. 
- Each time I open a FireCMS list view for this collection it fetches all 11000 documents.

**This behaviour is undesirable and should be omitted.**

**Comment by fgatti675** [comment] 2021-06-04 11:37
Definitely not the intended behaviour!
FireCMS should paginate  data, unless you specify `pagination`: false
I will look into this

**Comment by fgatti675** [comment] 2021-06-04 14:15
@k00na I haven't been able to reproduce this!
Could you check the console and make a screenshot after scrolling down on your collection?
The number should increase 50 by 50, if the parameter was not changed or pagination disabled.
If you filter by the verbose log messages you should see something like this:
<img width="643" alt="Screenshot 2021-06-04 at 16 14 42" src="https://user-images.githubusercontent.com/5120271/120815311-fb0db580-c54f-11eb-843a-8b85f213859e.png">

**Comment by fgatti675** [comment] 2021-06-16 18:36
Hey @k00na did you have the time to verify this?

**Comment by fgatti675** [comment] 2021-06-21 14:44
Hi @k00na 
You were right!
The collection views are loading the documents using pagination correctly but there is a sneaky Export component that was fetching all the documents eagerly, which was not intended. Now it will happen only on opening the dialog but we are working on an additional confirmation dialog for large collections.
Thanks for the catch!
It is fixed in version 0.41.1

**Closed by fgatti675** 2021-06-21 14:44 UTC
