### ISSUE TITLE
Attempted import error: 'useBlocker' is not exported from 'react-router-dom'.

### ISSUE THREAD

**Issue by ashutosh-singh-git** [Camberi/firecms#146] opened 2021-10-19 04:47 UTC
Getting Attempted import error:

package.json 
`{
  "name": "my-cms",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@camberi/firecms": "^1.0.0-beta2",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/icons-material": "5",
    "@mui/lab": "^5.0.0-alpha.49",
    "@mui/material": "5",
    "@mui/styles": "5",
    "firebase": "9",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router": "^6.0.0-beta.7",
    "react-router-dom": "^6.0.0-beta.7",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

Node Version:
`v12.20.0`
Npm Version:
`6.14.8`
Yarn version:
`1.22.10`

Tried via yarn and node. Unable to kickstart project. Did upgrading of node version as well. Please suggest anything which works

**Comment by fgatti675** [comment] 2021-11-12 12:27
Fixed in version 1.0.0-beta3!

**Closed by fgatti675** 2021-11-12 12:27 UTC
Labels: bug

**Comment by Fredleig** [comment] 2021-11-24 08:02
`"react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.0.2",`
    the problem is relevant

**Comment by luisluft** [comment] 2021-12-10 14:36
Getting the same error with these versions:
`    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^6.0.2",`

**Comment by Lau08** [comment] 2024-09-24 13:37
Is this still happening for `` "react": "^18.2.0", "react-dom": "^18.2.0", "react-router-dom": "^6.21.1", `` ? I still see the error that useBlocker is not exported. Is there a workaround to block going to another route when there are unsaved changes?
